# Generated by Django 3.2.5 on 2021-07-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='num',
        ),
        migrations.AddField(
            model_name='sortie',
            name='num',
            field=models.CharField(default='00101', max_length=10),
            preserve_default=False,
        ),
    ]
