# Generated by Django 3.2.5 on 2021-07-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=50, unique=True)),
                ('buying_price', models.FloatField()),
                ('retail_price', models.FloatField(blank=True, null=True)),
                ('wholesale_price', models.FloatField(blank=True, null=True)),
                ('basically_content', models.FloatField(blank=True, null=True)),
                ('qte_stock', models.FloatField()),
                ('qte_min', models.FloatField(default=5)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entrance', models.DateField(auto_now_add=True)),
                ('type_entrance', models.CharField(max_length=20)),
                ('buying_price', models.FloatField()),
                ('qte', models.FloatField()),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.articles')),
            ],
            options={
                'db_table': 'Entrance',
            },
        ),
    ]
