# Generated by Django 3.2.5 on 2021-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'Others',
            },
        ),
    ]
